### ISSUE TITLE
Need your help

### ISSUE THREAD

**Issue by gabalicious** [karlg100/frigidaire#2]
Hi Good Sir,

Great work so far.  It seems I'm connecting with the API but My AC doesn't work anymore.

Either it's so cold that my AC doesn't work or something happened when I started using this library.  I'll update you in a bit.  In the mean time what data can I provide you that will allow you to assist me.

**Comment by karlg100** [comment]
try turning off the plugin, wait a while and then see if the stock mobile app will allow you to remote control.  while engineering this, I've had it where the plugin may try too many times and cause your IP address to be blocked for a period of time at Frigidaire's servers.  don't worry, as it seems this is auto cleared after a short period of time.

**Comment by karlg100** [comment]
are you still having issues?  it seems others were having problems, but things have sorted out in the last couple months with connectivity.

**Comment by karlg100** [comment]
going to close for now as I believe these issues have gone away.
