### ISSUE TITLE
"New" Frigidaire app/api questions

### ISSUE THREAD

**Issue by dcousineau** [karlg100/frigidaire#4]
Hey, I just got a brand new cool connect window AC and this plugin doesn't appear to work, and I'm thinking it has to do with Frigidaire having a new app (https://apps.apple.com/us/app/frigidaire-2-0/id1500302958).

Am I right in my assumption that this is _not_ the api/app you reverse engineered?

If so, I started playing around with Charles to see if maybe I could inspect what requests were being made and I'm pretty sure this app is actually doing certificate pinning which means I got nothing. Did you have to go through a similar process or have any advice beyond some of the instructions I found of jailbreaking my device to install a modified ipa file?

**Comment by simonsaysjake** [comment]
@dcousineau were you able to figure this out? I have the same issue

**Comment by dcousineau** [comment]
No. I think Frigidaire's app team did too good of a job locking things down so any reverse engineering required is beyond my feeble capabilities. C'est la vie.

**Comment by amaisano** [comment]
Frigidaire just deprecated the original (1.0) app, and now only uses 2.0. This completely breaks this plugin. Is there any workaround? Seems like the new API is at https://www.frigidaire.com/api/userapi/getuser

**Comment by marekbrz** [comment]
Check out my latest pull request, which should solve this issue!

**Comment by karlg100** [comment]
PR merged.  Thanks @marekbrz!

**Comment by karlg100** [comment]
I'm getting reports the patch is working well for folks.  I'm going to close this issue!  Thanks again @marekbrz!
