### ISSUE TITLE
uhhh "feature request" maybe? node red.

### ISSUE THREAD

**Issue by y8s** [karlg100/frigidaire#9]
I know nothing about writing my own nodes for nodered. it would be awesome if this were packaged up into one.

Just throwing the idea out into the aether.

**Comment by karlg100** [comment]
So, NodeRed can used this module as a library to interact with your devices.  Really that belongs as a new library, like the Frigidaire-homebridge plugin.  Going to close this as we won't be adding this to this project, unless changes need to be made to support a NodeRed plugin.
